"Documentation":
  - changed-files:
      - any-glob-to-any-file: ["docs/**", "README.md"]
  - head-branch: ["^docs"]

"Enhancement":
  - head-branch: ["^feature", "^feat"]

"Bug":
  - head-branch: ["^fix", "^bugfix", "^hotfix"]

"Component":
  - changed-files:
      - any-glob-to-any-file: ["src/components/**"]

"Styling":
  - changed-files:
      - any-glob-to-any-file: ["**.scss"]

"GitHub Actions":
  - changed-files:
      - any-glob-to-any-file: [".github/**"]